// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD45eQSv1jFtr0cgS6UJ-xv0FQ94tFd67Q',
    appId: '1:903879172585:web:aaf965ca10b88fa5b66b78',
    messagingSenderId: '903879172585',
    projectId: 'foodpartner-717d3',
    authDomain: 'foodpartner-717d3.firebaseapp.com',
    databaseURL: 'https://foodpartner-717d3-default-rtdb.firebaseio.com',
    storageBucket: 'foodpartner-717d3.appspot.com',
    measurementId: 'G-K42H8LY01P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeGei232YiOWduWe2Vmp4ljFs-pl1wpLc',
    appId: '1:903879172585:android:91c8c632428426c5b66b78',
    messagingSenderId: '903879172585',
    projectId: 'foodpartner-717d3',
    databaseURL: 'https://foodpartner-717d3-default-rtdb.firebaseio.com',
    storageBucket: 'foodpartner-717d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNOP3kEk-oUzRVdCyByy2daah21g1GVV8',
    appId: '1:903879172585:ios:c016d9b0399f1df3b66b78',
    messagingSenderId: '903879172585',
    projectId: 'foodpartner-717d3',
    databaseURL: 'https://foodpartner-717d3-default-rtdb.firebaseio.com',
    storageBucket: 'foodpartner-717d3.appspot.com',
    iosBundleId: 'com.example.foodpartnerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNOP3kEk-oUzRVdCyByy2daah21g1GVV8',
    appId: '1:903879172585:ios:c016d9b0399f1df3b66b78',
    messagingSenderId: '903879172585',
    projectId: 'foodpartner-717d3',
    databaseURL: 'https://foodpartner-717d3-default-rtdb.firebaseio.com',
    storageBucket: 'foodpartner-717d3.appspot.com',
    iosBundleId: 'com.example.foodpartnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD45eQSv1jFtr0cgS6UJ-xv0FQ94tFd67Q',
    appId: '1:903879172585:web:e5558278529ea098b66b78',
    messagingSenderId: '903879172585',
    projectId: 'foodpartner-717d3',
    authDomain: 'foodpartner-717d3.firebaseapp.com',
    databaseURL: 'https://foodpartner-717d3-default-rtdb.firebaseio.com',
    storageBucket: 'foodpartner-717d3.appspot.com',
    measurementId: 'G-4EK2VP66M4',
  );

}